ubuntu/WSL

wsl-builder/build-wsl
The build script optionally build a rootfs from the ppa and start a
github action wsl build.
It supports all options from the client, takes a token created on the
WSL project.
=> Add build script

wsl-builder/prepare-assets/assets.go
Support first build of a new release in development without its meta/ directory.
=> Fix CI prepare-assets for new release without an initial meta/ directory

wsl-builder/prepare-build/build.go, wsl-builder/prepare-build/main.go
With the proposed changes one now can `./prepare-build.exe prepare UbuntuPreview build.txt ~/Downloads/impish_exit_0_oobe.tar.gz::amd64` for example. That command will copy the file from that path supplied if valid, instead of downloading from some cloud, which improves testability by enabling developers to customize their images as they wish and ensure the WSL building workflow stays the same.
=> Prepare-build now can copy a local rootfs file.

wsl-builder/build-wsl
Most of the tools are using ppa:<owner>/<ppa>, but not the launchpad
API. Allow for this syntax by stripping the prefix if present.
=> Relax ppa syntax by allowing ppa: prefix in builder

build-remote
This avoids stuttering in naming. It’s not referenced anywhere in the
project.
=> Rename and move builder tool to build-remote

DistroLauncher/.clang-tidy, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/OOBE.cpp, DistroLauncher/OOBE.h, DistroLauncher/ProcessRunner.cpp, DistroLauncher/ProcessRunner.h, DistroLauncher/WSLInfo.cpp, DistroLauncher/WSLInfo.h, DistroLauncher/WindowsUserInfo.cpp, DistroLauncher/WslApiLoader.cpp, DistroLauncher/WslApiLoader.h, DistroLauncher/stdafx.h, wsl-builder/lp-distro-info
There is a --text parameter added to wsl-setup, which starts the TUI instead of the snap GUI. We need to add it dynamically from the launcher:
- if wslg is not installed
- or if current distro is using wsl 1
To achieve that, WSLApiLoader was modified to expose one hidden function `WslGetDistributionConfiguration()`, which can report the recently installed distro subsystem version, default environment variables etc. For this PR the only relevant piece of information is the subsystem version.
There could be other ways to find that information, like querying the Windows registry for the default system version. That idea in particular could lead into crashes if the OOBE is ran in the future in reconfigure mode, for instance, under a distro with the version modified to WSL 1.
The graphics …
=> Fallback OOBE into text mode if graphics are not supported

DistroLauncher/DistroLauncher.cpp, DistroLauncher/messages.mc, README.md
Craig Lowen reported having changed the DistroLauncher code to improve the WSL experience, redirecting the user to the docs web page in case of virtualization being disabled. Also, noticed the [README file was updated recently](https://github.com/microsoft/WSL-DistroLauncher/commit/28d908d9605052c0864138ed98e858d0979f73f7). This PR captures both changes and preserves the original authors, as it should be.
=> Upstream updates

DistroLauncher/DistroLauncher.vcxproj, meta/Ubuntu/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/Ubuntu22.04LTS/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/UbuntuPreview/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj
Per conversation on https://github.com/microsoft/WSL-DistroLauncher/issues/103 the recommendation is to upgrade to the latest SDK version. The other option would be define the constant in our sources.
```cpp
#define HCS_E_HYPERV_NOT_INSTALLED _HRESULT_TYPEDEF_(0x80370102L)
```
Since GitHub documentation says this version of the SDK is supported on the Windows runners, I opted in for the first option. Should the upstream implement any other fix I'll revisit this topic, but for now this is enough our CI.
=> Upgraded SDK version to fix HCS_E_HYPERV_NOT_INSTALLED undeclared

DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj, DistroLauncher-Tests/DistroLauncher-Tests/LocalNamedPipeTests.cpp, DistroLauncher-Tests/DistroLauncher-Tests/LocalNamedPipeTests2.cpp, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/local_named_pipe.cpp, DistroLauncher/local_named_pipe.h
Named pipe will be used for console redirection. This pipe technique has been tested with C++ and Dart console apps and Flutter GUI apps to make sure it works. 
A console service will use this class to activate and deactivate redirection according to the state of the launcher application. Handling it thru Win32 API all by itself can become really tricky. This class should facilitate that task.
Tests added assert the logic and invariants of this abstraction, not the pipe functionality.
This component is not yet connected to the launcher application. No change in behavior of the app should be noticed by this addition. Integration will happen after adding all necessary components.
The foreseen usage for this component is like the snippets below:
```cpp
auto console = …
```
=> Created an abstraction for the Win32 named pipe.

wsl-builder/common/releasesinfo.go
We now want an image starting being automatically built 3 weeks before a
release date.
Co-authored-by: Carlos Nihelton <carlos.santanadeoliveira@canonical.com>
=> Change rule for building 3 weeks before release

DistroLauncher-Tests/DistroLauncher-Tests/ConsoleServiceTests.cpp, DistroLauncher/console_service.h, DistroLauncher/local_named_pipe.cpp, DistroLauncher/local_named_pipe.h
While integrating the console service with the splash controller under development, it was noticed some gaps in the console handling:
- Hiding console wouldn't work in the Windows Terminal
- GetConsoleWindow() misleads if the app is not running in the old console
- The order of assignment of handles and file descriptors was hiding Linux apps stdout and stderr.
- Splash controller will need to know the console window handle at some point.
- Console service sometimes needs to disconnect the pipe before its destruction.
- Fake (test) pipes had to update their API.
This PR fixes all those situations.
=> Console handling enhancements

wsl-builder/prepare-build/go.sum
With the addition of the uuid package as dependency the workflow is broken at the go build step due the missing dependency.
=> Attempt to fix build-wsl workflow

.github/workflows/detect-update-releases.yaml, DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, DistroLauncher-Appx/Terminal/Fragments/terminal.json, meta/Ubuntu/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/Ubuntu/generated/DistroLauncher-Appx/Terminal/Fragments/terminal.json, meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/Terminal/Fragments/terminal.json, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/Terminal/Fragments/terminal.json, meta/Ubuntu22.04LTS/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/Ubuntu22.04LTS/generated/DistroLauncher-Appx/Terminal/Fragments/terminal.json, meta/UbuntuPreview/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/UbuntuPreview/generated/DistroLauncher-Appx/Terminal/Fragments/terminal.json, wsl-builder/prepare-build/go.sum
Terminal theme fix, with the platform number fix which pass also in CI.
Note that it can look weird that the json is under an "Image" item type. There is no defined name, but I tried "None", "Item" and a set of assets + others and they do not work.
Image does not seem to have any side-effects and works well. There is no official guide on the Windows Terminal example for now, so let’s use this for now.
This branch was both tested on CI (and package installed from CI) from https://github.com/ubuntu/WSL/actions/runs/1887626864 and with Visual Studio, local sideloaded build.
=> Terminal theme fixes

DistroLauncher-Tests/DistroLauncher-Tests/SplashControllerTests.cpp, DistroLauncher/splash_controller.h
During tests it was noticed that deadlocks could occur if the user closes the splash window before the application restored the console. We need to have the operating system to notify the application code when the child process ends, if that ever happen, asynchronously. Using only raw Win32 API requires multithreading. 
The heart of the changes are the pair `RegisterWaitForSingleObject/UnregisterWait`. The first assigns a thread from the system's thread pool to execute a callback we supply whenever the monitored object becomes signaled (in this case the splash process handle being closed). As this will be executed in another thread, care must be taken in the callback itself to make the call thread safe. As this monitoring is demanded only by the case of unexpected close-out (most likely …
=> Fix on close

DistroLauncher-Appx/Terminal/Fragments/terminal.json, meta/Ubuntu/generated/DistroLauncher-Appx/Terminal/Fragments/terminal.json, meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/Terminal/Fragments/terminal.json, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/Terminal/Fragments/terminal.json, meta/Ubuntu22.04LTS/generated/DistroLauncher-Appx/Terminal/Fragments/terminal.json, meta/UbuntuPreview/generated/DistroLauncher-Appx/Terminal/Fragments/terminal.json
Remove acrylic as discussed last week.
I did a rebuild of Ubuntu Preview, and when installing it on ubuntudev1, the expected color profile (generated with Preview) is selected, so nothing more to be done in this regard AFAIK.
=> Remove acrylic from theme

DistroLauncher/WSLInfo.cpp, DistroLauncher/WSLInfo.h
Those files were selected to receive the systemd related functions. As they were, CI would generated formatting and linting warnings when pushing systemd related code.
This PR acts as a preparation, anticipating and avoiding those warnings. At the same time, some conceptual changes moving code from `Helpers` namespace (which should stay upstream-only) to `Oobe::internal`. One function was left off this code move to avoid touching other files. They will be treated at a proper time.
Yet, some behavior changes were done here:
- Corrected the distroVersion interpretation.
- Added a check for the $DISPLAY env var being set for Wslg detection.
=> WSLInfo.cpp/h maintenance

.github/workflows/build-wsl.yaml
Currently ISO Tracker notifications fail as there is a typo in the script path - apologies!
=> Typo fix in the script path for isotracker notification.

wsl-builder/common/go.mod, wsl-builder/prepare-assets/assets.go, wsl-builder/prepare-assets/go.mod, wsl-builder/prepare-build/build.go, wsl-builder/prepare-build/buildGHMatrix.go, wsl-builder/prepare-build/go.mod, wsl-builder/prepare-build/main.go
We are now using wsl/ instead of distrolauncher in the package name.
Co-authored-by: Jean-Baptiste Lallement <jean-baptiste@ubuntu.com>
=> Rename go build projects with real github path

DistroLauncher/ExitStatus.cpp, DistroLauncher/OOBE.cpp
Not sure why this is happening, but sometimes trying to access `\\wsl$\<DISTRO>` blocks forever while `\\wsl.localhost\<DISTRO>` works.
While no enlightment comes to this issue, let's workaround.
Although this PR looks huge, that's mainly due formatting. The file `OOBE.cpp` predates the current CI and would trigger a lot of warnings. For actual content review focus on commit fbada24edb1ddcffef99cd4946068eb32d77b0bc
Now all filesystem accesses thru WSL Service in the launcher is done with `\\wsl.locahost` path prefix.
=> wsl$ versus wsl.localhost

DistroLauncher/DistroLauncher.cpp, DistroLauncher/OOBE.cpp, DistroLauncher/OOBE.h
My previous solution was too naive. Upon conclusion of the installation the rest of the upstream "command line parsing" code understood the existance of the option `--skip-installer` as an argument error and terminated the application when we should run the shell instead.
Now we detect that specific command line argument with a function call that removes it, if exists. So, after installation, the rest of the existing code in `DistroLauncher.cpp` can keep working as if nothing ever changed.
=> Removes the option --skip-installer from the arguments vector

DistroLauncher/ExitStatus.cpp, DistroLauncher/OOBE.cpp
Previously we had one extra run with root.
Now we configure the default user first, then log with it if we get to the shell.
There is no proper shutdown for this case, because if it was not install only, then the upstream code will run the shell with the default logged user. We could `exit(0)` at the shutdown point, but I don't really see subiquity requesting to shutdown in the first place.
The functions responsible for parsing the `/run/launcher-command` file and taking the actions (configure the default user and rebooting the distro) were previously reviewed, but never integrated. The integration is essentially calling `Oobe::ExitStatusHandling()`, which replaces a bunch of older code that attempted to do a similar, but simpler, parsing.
=> Fix the distro reboot behavior.

DistroLauncher/DistroLauncher.cpp, DistroLauncher/OOBE.cpp
Now users by default get the upstream experience.
To leverage the OOBE user is required to add the CLI option `--enable-installer`.
This is the expected result:
=> Inverts the skip-installer option logic

DistroLauncher/DistroLauncher.cpp, DistroLauncher/OOBE.cpp, DistroLauncher/OOBE.h
This should be reverted once the rootfs gets fixed. For now, this should be enough.
The function could be implemented by just hardcoding two commands, like:
```cpp
g_wslApi.WslLaunchInteractive(L"groupadd admin 2>/dev/null", false, &exitCode);
g_wslApi.WslLaunchInteractive(L"groupadd netdev 2>/dev/null", false, &exitCode);
```
But I don't quite like hardcoding things all around, so I'd rather do some extra work to make a little more generic. Should we need to add another group in the mean time it's just a matter of adding one more group at the call site, instead of another long command. 
Yet, if you think this is overkill, just let me know.
=> Workaround missing groups in the current rootfs.

DistroLauncher/OOBE.cpp
Besides the typo in the variable name, while checking for the existence of the OOBE, this function caused some undesired output to console with not much context or information. This PR silences it, since for this function, checking the exit code is enough.
=> Silent which

.github/workflows/build-wsl.yaml, wsl-builder/notify-isotracker
We also run notify-isotracker in debug mode temporarily - this should be switched off after we confirm all is good.
=> Add some additional debug information to notify-isotracker runs

DistroLauncher/console_service.h
It's been observed with experimentation that sometimes we fail to find console window. Making the main thread sleep for a few milisseconds reduced dramatically the occurences of failure on call to `FindWindow()`.
=> Decreases the chance of failure to find Windows terminal window

DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj, DistroLauncher-Tests/DistroLauncher-Tests/ExtendedCliParserTests.cpp, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/extended_cli_parser.cpp, DistroLauncher/extended_cli_parser.h, DistroLauncher/messages.mc
With PR #123 , #125 and #129 we added a new command line option to the launcher: `--enable-installer`.
This PR presents a more flexible way to add new command line options while preserving the existing ones, including the upstream. It is designed to avoid interaction with the upstream "command line parsing" (a series of if-else clauses in `DistroLauncher.cpp`) by removing the "extended" options from the vector of arguments (which is passed by a mutating reference).
The parsing output is a variant of types representing the tasks the launcher is supposed to do plus a `std::monostate` to represent the not-our-business options, which must be handled by the upstream code. Think of `std::monostate` like a `nil` type for variants.
Shall we want to support more command lines arguments in the …
=> Extended command line options.

.github/workflows/build-wsl.yaml, .gitmodules, DistroLauncher-Appx/Directory.build.props, DistroLauncher-Appx/MyDistro.appxmanifest, DistroLauncher-Appx/MyDistro.appxmanifest.tmpl, meta/Ubuntu/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/Directory.build.props, meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu18.04LTS/src/DistroLauncher-Appx/Directory.build.props, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/Directory.build.props, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu20.04LTS/src/DistroLauncher-Appx/Directory.build.props, meta/Ubuntu22.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/UbuntuPreview/generated/DistroLauncher-Appx/MyDistro.appxmanifest
This PR aims to bring the Flutter splash screen as a submodule of the launcher and bundle its build artifacts into the generated appx bundle. This is done by:
- Adding the Flutter repository as a submodule;
- Making the CI fetch and build it;
- Make the Appx project automatically bundle the Flutter build artifacts. This is achieved by the `Directory.build.props` file added to the Appx project directory. To make it specific to the releases that feature the OOBE, the referred build system file is added to the `meta/generated` directories. They are not available in the build tree by default.
- Ensuring the availability of the VC++ runtime on the target host. Achieved by adding the PackageDependency declaration to the `MyDistro.appxmanifest` files. This requires testing on a host we can …
=> Adding the Flutter splash project as part of the bundle

DistroLauncher-Tests/DistroLauncher-Tests/SplashControllerTests.cpp, DistroLauncher/splash_controller.h
With this change the splash application should stay on top when visible. This ensures the OOBE GUI won't pop up in front of it disruptively, allowing the launcher to control it more smoothly without surprising the user.
This always on top behavior could be annoying, but the slide show will stay for a short period of time, so we should be fine.
=> Ensures splash always on top while visible

DistroLauncher/ExitStatus.cpp
Without the line break if user has two running distros and the name of one of those is a substring of the other,
the algorithm fails to detect the substring distro had shutdown.
For instance, let's say you have `Ubuntu` and `Ubuntu20.04LTS` running and you want to shutdown `Ubuntu`. The existing logic would fail to detect that `Ubuntu` shutdown because it would always find a match on `Ubuntu22.04LTS`.
=> Corrects substring matching on distro shutdown.

.github/workflows/clang_lint/msbuild/clang_tidy_runner.py, .github/workflows/qa.yaml, DistroLauncher-Tests/DistroLauncher-Tests/InstallerControllerTestPolicies.h, DistroLauncher/ApplicationStrategy.cpp, DistroLauncher/ApplicationStrategy.h, DistroLauncher/Win32Utils.cpp, DistroLauncher/Win32Utils.h, DistroLauncher/console_service.h, DistroLauncher/installer_controller.h, DistroLauncher/installer_policy.h, DistroLauncher/splash_controller.h, DistroLauncher/state_machine.h
This adds the capability to find the WSLg window where the OOBE GUI is displayed and controlling its visibility while synchronizing with the splash application, to ensure a smooth transition.
For the console, upon restoration, its resized to match the splash size and placement, so it can stay nicely hidden by the splash until it disappears. Also, asking to hide the splash now blocks while it stays visible.  This prevents other windows from popping up in front of it and causing disruption to the user attention.
I wanted to do the very same with the WSLg window, but moving it programmatically causes a very strange behavior. I'll investigate first whether this has been fixed in the latest updates or not and report a bug if not. It behaves as if the window had moved but the internal widgets …
=> Hides the OOBE window

DistroLauncher-Tests/DistroLauncher-Tests/ExtendedCliParserTests.cpp, DistroLauncher/Application.h, DistroLauncher/ApplicationStrategy.cpp, DistroLauncher/ApplicationStrategy.h, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/extended_cli_parser.cpp, DistroLauncher/extended_cli_parser.h, DistroLauncher/extended_messages.h, DistroLauncher/installer_controller.h, DistroLauncher/messages.mc, DistroLauncher/stdafx.h, meta/Ubuntu18.04LTS/generated/DistroLauncher/extended_messages.h, meta/Ubuntu18.04LTS/src/DistroLauncher/extended_messages.h, meta/Ubuntu20.04LTS/generated/DistroLauncher/extended_messages.h, meta/Ubuntu20.04LTS/src/DistroLauncher/extended_messages.h
Notice that the `=` signal is mandatory and spaces around are not tolerated in the current implementation. That can be enhanced if necessary, but will require more cleverness.
There is a header file trick to redefine the `MSG_USAGE` to `MSG_USAGE_EXTENDED` for the releases that support the OOBE. The header file `extended_messages.h` does this redefinition. For the releases that won't offer the OOBE, there should be an empty version of this file in meta subtrees, so the workflow can do the selection work.
With this implementation there is a nesting semantics on whether the shell should be available in the end or not (mandated by the argument `install` in the argv[1] position) versus whether the installer should be GUI, TUI or none (the original experience).
There are some compile-time …
=> Reverts `--enable-installer` option into a more complete `--ui=` command line.

DistroLauncher/ExitStatus.cpp, DistroLauncher/OOBE.cpp, DistroLauncher/OobeDefs.h, DistroLauncher/WSLInfo.cpp, DistroLauncher/WSLInfo.h, DistroLauncher/Win32Utils.cpp, DistroLauncher/Win32Utils.h, DistroLauncher/installer_policy.h
The result of the function call depends on the operating system version, which is obtained by reading the build number from the registry.
To avoid linting complains, some reformattings were done in `ExitStatus.cpp`. Since we are touching that file, the function `ExitStatusHandling()` was slightly simplified since the experimentation has shown that we can use wide characters in file paths to open files in the Linux file system. To simplify it further, I unified the return type of the error handling code into one single kind of exception to avoid slicing when returning errors.
=> Replace \\wsl$ or \\wsl.localhost path prefix with a function call

DistroLauncher/ApplicationStrategy.cpp, DistroLauncher/ApplicationStrategy.h
The `using Mode = InstallerController<>::Mode;` statement was available only for x64. My bad. This fixes it and a related mistake in the cpp file as well.
=> Fix build error due Mode undeclared for ARM64

wsl-builder/prepare-build/build.go
This was to broad and was conflicting with API version.
=> Fix minor version build replacement

DistroLauncher/ApplicationStrategy.cpp, DistroLauncher/installer_controller.h, DistroLauncher/installer_policy.h
And ensures the HRESULT value returning from a failed operation is preserved. Also increases the overall duration of the function  `poll_success()` to decrease he likelyhood of it causing an OOBE crash on slower machines.
=> Makes use of more specific HRESULTS in installer_controller

DistroLauncher/WindowsUserInfo.cpp
Most of this PR is reformattings to avoid unrelated linting complaints.
The important point of it is the following change:
```diff
inline void PrintLastError()
{
HRESULT error = HRESULT_FROM_WIN32(GetLastError());
-            Helpers::PrintErrorMessage(error);
+            wprintf(L"Recovering user information failed with the code: %lx\n", error);
}
```
The rest is details.
This avoids the message to appear with the "Error: " prefix, thus reducing its level of importance. In fact, this is used for when GetUserNameEx and GetUserLocale functions fail, which is not a big thing.
Since this call `BOOLEAN ret = GetUserNameExW(EXTENDED_NAME_FORMAT::NameDisplay, userRealName, &nSize);` is the offeding one due the VM user not being fully setup in a domain with its detailed name registered, a …
=> Demote userinfo errors

DistroLauncher/ApplicationStrategy.cpp, DistroLauncher/installer_controller.h
In attempt to void nested-if clauses I made a silly mistake in the switch statement causing it to slip through into Mode::Gui case without actually reading the updated value inside the variable uiMode.
Also, a small change in the ApplicationStrategy.cpp to ensure the failing HRESULT will be preserved for the ARM64 platform as we did previously for the x64.
=> Fix GUI support autodetection

DistroLauncher/installer_policy.h
Reported that sometimes the OOBE GUI window appeared behind other random windows.
We cannot control where WSLG will render any Linux window, but once we find it, we can control its placement.
The reported issue was due the routine that attempts to find the GUI window was timing out.
This increases the time out duration. Moving that window is also an option, but it may mess with WSLG recognition of the window controls, so let's take the easy path for now.
=> Reduces the chance of not finding the GUI window

DistroLauncher-Tests/DistroLauncher-Tests/InstallerControllerTestPolicies.h, DistroLauncher-Tests/DistroLauncher-Tests/InstallerControllerTests.cpp, DistroLauncher/ApplicationStrategy.cpp, DistroLauncher/installer_controller.h
Previously OOBE GUI placement was controlled by WSLG only. Sometimes it appeared behind other random windows.
With this change we leverage the same mechanisms used for interactive install to ensure the OOBE GUI will appear on top.
That requires breaking the reconfig in more states if GUI mode, reusing the same states related to the interactive install, 
maximizing reuse of the state machine components.
TUI reconfig remains unchanged.
Tests and comments were revised to reflect those changes as well.
=> Ensures OOBE will be presented on top on Reconfig.

DistroLauncher/installer_policy.h
Current working directory permissions may affect Subiquity startup or cause crashes.
OOBE should never be launched in cwd.
=> Never launch OOBE in current working directory

wsl-builder/prepare-build/buildGHMatrix.go
As we are in a particular state with no release to build at all, then
the slice of matrixEleme is deserialized to null, which is json
compatible.
It seems that GitHub Actions don’t like that and still expect an
iterable.
Consequently, this is a tentative fix to set it to an empty slice
instead of nil, so that GitHub Action could try iterating over it and do
nothing.
=> Try fixing dailies with no development releases

meta/SBConfig.json
This prevents making every new update for people only having the link.
We keep previous app state.
=> Keep last store visibility state

.github/workflows/build-wsl.yaml, wsl-builder/prepare-build/buildGHMatrix.go
This ensure that we don’t have Includes: [] which is not supported by
GitHub Actions: "At least one vector element is required".
=> Avoid building CI matrix when there is no distro to build

DistroLauncher/installer_policy.h
Windows 11 build 22598 users reported GUI mode installation reported failed but the background tasks had succeeded.
Thus, when applying the fallback with the same username, that method also failed.
OOBE is returning a failed exit code, but Subiquity concluded its work.
This ensures to return 0 if server-state is successful.
Returns OOBE error code otherwise.
Yet, further investigation on the OOBE side is required to understand why it's reporting failure if the installation completed and what is the relationship between the latest Windows and WSL updates and the OOBE reporting failure.
Fixes #180
=> Prefers server-status over OOBE exit code

DistroLauncher/WindowsUserInfo.cpp
Errors herein printed are harmless to users, they are interesting to developers only. Thus instead of being displayed to users, they should be logged in a debug channel, where users won't see them but developers can in case more severe issues get reported. Since we don't yet have a proper logging, this PR removes printing any error messages related to acquiring user name and locale information.
Fixes #170 .
Leaving a TODO to place those to a debug channel for when we land a proper logging mechanism.
=> Removes prefill feature error messages

DistroLauncher-Appx/MyDistro.appxmanifest, DistroLauncher-Tests/DistroLauncher-Tests/ExtendedCliParserTests.cpp, DistroLauncher/Application.h, DistroLauncher/ApplicationStrategy.cpp, DistroLauncher/ApplicationStrategy.h, DistroLauncher/console_service.h, DistroLauncher/extended_cli_parser.cpp, DistroLauncher/extended_cli_parser.h, meta/Ubuntu/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu18.04LTS/generated/DistroLauncher/extended_messages.h, meta/Ubuntu18.04LTS/src/DistroLauncher/extended_messages.h, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu20.04LTS/generated/DistroLauncher/extended_messages.h, meta/Ubuntu20.04LTS/src/DistroLauncher/extended_messages.h, meta/Ubuntu22.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/UbuntuPreview/generated/DistroLauncher-Appx/MyDistro.appxmanifest
This PR is somewhat opinionated, so I'd expect some pushback.
The current implementation hides the console window unconditionally, behavior which drove issue #176 .
Ideally the console window should be hidden if it was only opened for the solely purpose of invoking the launcher to install the distribution, which is the case when the user launches it from start menu or from the store, right after installing the app. It could also be launched from the `Run` dialog (I don't know a better name for that, the one we get when we hit Super+R). In that case the user could pass an arbitrary combination of command line arguments and still a console window would be opened dedicated to the launcher process.
In contrast, not even for the empty command line case we would want to hide the console window …
=> Hide console only if it's dedicated to the launcher process

build-remote
Those changes are basically the following:
- Add support for anonymous LP login - I suppose using `login_with()` might have some uses (like for private PPAs), but in general for normal operation we don't really need to be logged in. Especially when running without any credentials in automation (like cdimage!).
- Add support for HTTPS proxy specification - this was needed due to the firewall situation on ancientminister.
- Remove usage of 3.9+ `removeprefix()` - for getting rid of the "ppa:" prefix, let's have a non-3.9+ method of stripping by providing a helper function with the good-ol' startswith()+slicing. This was needed as we don't have `removeprefix()` on ancientminister yet.
=> build-remote: A few changes that were needed for usage on cdimage

meta/SBConfig.json
SB is failing due to missing parameter. Check if the missing one is
visibility which would be then required.
Co-authored-by: Jean-Baptiste Lallement <jean-baptiste@ubuntu.com>
=> Try readding Visibility field

.github/workflows/build-pr.yaml
Use for now a static rootfs, do not do any other change, and pull
everything to latest.
This ensures we can always build before merging our windows app package
and attach it to the PR to sideload, without any further change.
=> Build windows app package on PR

.github/workflows/sync-gh-jira.yaml
Use a default "jira" tag to import bugs to our Jira instance.
=> Enable github to jira bug synchronization

DistroLauncher/ApplicationStrategy.cpp
When using a rootfs corresponding to Ubuntu 20.04 LTS, a `std::bad_optional_access` exception is thrown.
This is fixed by adding a check around it.
=> Added check around optional splash access

DistroLauncher/WSLInfo.cpp
There is a lambda that we know always returns a value, but the compiler is unaware of this.
This fix adds a sanity test to ensure it trully never happens (in debug mode), and tells the compiler so in Release mode.
=> Fix no-return lambda warning

.github/workflows/qa.yaml
When you push twice in a row, CI jobs run twice. The runs for the old commits are redundant.
The biggest effect is that the Github commenter will start spamming threads when you push two commits in a row (for instance when you accept more than one of its suggestions).
This PR changes it so that, in pull requests, a newer commit will cancel old QA runs. If necessary I can also apply it to `build` and `run-tests`, but these are less anoying.
=> QA is cancelled when a new commit is pushed

.github/workflows/sync-gh-jira.yaml
The [ubuntu/sync-issues-github-jira](https://github.com/ubuntu/sync-issues-github-jira) action can now convert GitHub Markdown to JIRA Markdown. However, this is only supported starting with Ubuntu 22.04 which is not yet `ubuntu-latest`.
Explicitly request `ubuntu-22.04`. This change can be reverted when GitHub changes `ubuntu-latest` to point at `ubuntu-22.04`.
Not sure how often y'all are using this but I thought it might be a nice addition 😄.
=> Bump runner version for the Jira sync workflow

DistroLauncher/ApplicationStrategy.cpp, DistroLauncher/Win32Utils.cpp, DistroLauncher/Win32Utils.h
Currently the splash executable (the slide show) is located inside the appx directory at the same level as the launcher. Soon we'll have the new OOBE located in the same directory, but a different filename. The patch feature being drafted in #217 will likely store files in a subdirectory as well. So, to avoid duplication, this PR extracts the logic to find this app root directory into it's own function, so we can append subdirectories and filenames as we wish.
The usage is illustrated in the `ApplicationStrategy.cpp` where we locate the `ubuntu_wsl_splash.exe` relative to that path.
=> This app rootdir

.github/workflows/build-pr.yaml
That workflow is quite slow, due the need to download and package a real rootfs.
We need to figure out ways to make it faster, but in the meanwhile, let's skip it for draft PR's until they are marked as ready for review.
=> Prevents running the build workflow on draft PRs

DistroLauncher-Tests/DistroLauncher-Tests/IniFindValueTests.cpp, DistroLauncher/WSLInfo.cpp, DistroLauncher/WSLInfo.h, DistroLauncher/Win32Utils.cpp, DistroLauncher/Win32Utils.h
That feature enables binding WSL 2 localhost to Windows localhost, thus enabling transparent connection through TCP where the client is running on the host while the server is running inside the WSL 2 distro, scenario expected by our OOBE. For security reasons, only localhost can connect to the server, thus this information is crucial.
That feature is enabled by default, but can be manually disabled by tweaking the `~\.wslconfig` file, which is a per-user configuration file that affects all distros running in the scope of the referred Windows user.
So to be able to read that configuration value we need to:
1. Find the user's home path;
2. Parse the file (ini parsing has been previously implemented)
3. look for the value of the entry [wsl2.localhostForwarding].
This will be used later in …
=> Enables checking if localhost forwarding is disabled

DistroLauncher/.clang-tidy, DistroLauncher/ApplicationStrategy.cpp, DistroLauncher/ExitStatus.cpp, DistroLauncher/OOBE.cpp, DistroLauncher/ProcessRunner.cpp, DistroLauncher/ProcessRunner.h, DistroLauncher/Win32Utils.cpp, DistroLauncher/console_service.h, DistroLauncher/extended_cli_parser.cpp, DistroLauncher/extended_cli_parser.h, DistroLauncher/installer_policy.h, DistroLauncher/local_named_pipe.h, DistroLauncher/state_machine.h
Only made changes in non-microsoft files. Applied most clang-tidy feedback from the last run in main (https://github.com/ubuntu/WSL/runs/7303623016?check_suite_focus=true).
**Solved**
- Most short-variable-name complaints
- Adding some consts
- `NULL` -> `nullptr`
- Removed some unused variable names in lambda arguments. Example: `[&](auto&&... s) { return E_UNEXPECTED; },` becomes `[&](auto&&...) { return E_UNEXPECTED; },`.
- Order of constructor list
**Not solved**
- Reasonable or standard short variable names (e.g: `ok` or `hr`)
- Some variables that I wasn't sure what to rename them to.
- Implicit casts from `BOOL` (Microsoft's typedef'd int) to `bool`.
=> Solved some clang-tidy complaints

DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj, DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj.filters, DistroLauncher-Tests/DistroLauncher-Tests/ExitStatusParserTests.cpp, DistroLauncher-Tests/DistroLauncher-Tests/ExtendedCliParserTests.cpp, DistroLauncher-Tests/DistroLauncher-Tests/IniFindValueTests.cpp, DistroLauncher-Tests/DistroLauncher-Tests/LocalNamedPipeTests.cpp, DistroLauncher-Tests/DistroLauncher-Tests/main.cpp
The idea is to link in the source files from the project, so their functionality can still be tested.
Ready
- Added DistroLauncher sources to Test solution
- Added onecore.lib to linker
- Added definition of `g_wslApi` in `main.cpp` (Needed by the compiler even if not used)
- Removed includes of sourcefiles
- Added a filter in VS project to keep test- and launcher-sources separate
=> Better testing proposal

DistroLauncher-Tests/DistroLauncher-Tests/ChildProcessTests.cpp, DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj, DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj.filters, DistroLauncher-Tests/DistroLauncher-Tests/FakeChildProcessImpl.cpp, DistroLauncher-Tests/DistroLauncher-Tests/FakeChildProcessImpl.h, DistroLauncher-Tests/DistroLauncher-Tests/SplashControllerTests.cpp, DistroLauncher/ChildProcess.cpp, DistroLauncher/ChildProcess.h, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/splash_controller.h, DistroLauncher/stdafx.h
The splash controller is made of a state machine and a strategy class full of static functions to encapsulate the Win32 API's with the duty of starting and controlling the slide show application. There are a few premises related to its job:
1. Launcher output stream must be succefully redirected so the child process can read it and display the messages.
2. The Flutter executable must exist.
3. Starting the application must succeed.
4. Detecting its HWND also succeeds.
It's quite easy to predict that the behavior of that class could be a nightmare of if-elses. That's why the state machine design.
Yet, the strategy class that feeds the controller with the Win32 capabilities is doing too much: controlling the application process and the application window. When porting the OOBE to Windows, …
=> Extracts the process handling out of the splash controller

wsl-builder/prepare-build/buildGHMatrix.go
My Go skills are a bit rusty, so I'd prefer asking review from an expert. 😄 
Per the CPC team information. Kinetic (22.10) and later versions are to be published to that location (see https://cloud-images.ubuntu.com/wsl/kinetic/ for instance). Previous versions stay in cloud-images.ubuntu.com.
This PR aims to let the build matrix routine to differentiate the base URI from where to download the images.
=> Enables downloading images from the c-i.u.c/wsl

.github/workflows/qa.yaml
Linting is quite resource consuming.
Only the sources inside `DistroLauncher/` are linted.
PR's which won't touch those files (or the workflow ones) will have QA skipped.
This will not skip run-tests workflow.
=> Skip C++ source linting for unrelevant PRs

DistroLauncher/ExitStatus.cpp
Filesystem calls in the context this PR touches could fail due user making some configuration to the distro preventing Windows from accessing the referred file as well as user permissions, since the affected function is no longer called only during distro setup.
Thus, this PR avoids exceptions been thrown due filesystem API errors. `std::bad_alloc` can still be thrown :D 
I preferred to go with the `error_code` API then the Pokémon approach (`catch (...)`).
=> Prevents filesystem exceptions

wsl-builder/prepare-build/buildGHMatrix.go
I was so happy with the new pipeline that I didn't notice the image naming scheme also changed. 😳
Older images scheme: `<codename>-server-cloudimg-<arch>-wsl.rootfs.tar.gz`.
With the new pipeline: `ubuntu-<codename>-wsl-<arch>-wsl.rootfs.tar.gz`.
Before:
After:
This PR complements #235 to adapt the image base name convention.
=> Adapts the image base name to the new pipeline

DistroLauncher-Tests/DistroLauncher-Tests/mock_api.cpp, DistroLauncher-Tests/DistroLauncher-Tests/mock_api.h, DistroLauncher-Tests/DistroLauncher-Tests/sudo_tests.cpp, DistroLauncher/sudo.h
This static function is problematic because the process it launches may outlive the user change.
The goal of the Sudo class is to abstract away these complexites, and this function failed to achieve this.
=> Removed Sudo::WslLaunch

.github/workflows/qa.yaml
GitHub history shows that succesful runs finish under 15 minutes long. Longer runs required manual cancellation.
Not sure the cause, but let's limit the runs to 20 minutes for now to avoid depending on manual cancellations, at least.
GitHub default limit seems too much: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
=> [CI] Sets a 20 min timeout for clang-tidy

DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj, DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj.filters, DistroLauncher-Tests/DistroLauncher-Tests/SetOnceNamedEventTests.cpp, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/DistroLauncher.vcxproj.filters, DistroLauncher/SetOnceNamedEvent.cpp, DistroLauncher/SetOnceNamedEvent.h
An abstraction on top of Win32 Named Events that can be set only once.
>NOTE: Win32 Events (named or unnamed) are resetable, meaning that one can toggle on-off as much as desired. They
can even be automatically reset by the OS, if configured to do so by the CreateEvent function. This class
restricts that behavior by closing the OS handle and nulling out the private field that would represent it, thus
rendering the object useless after being once set.
Usage
----
Ensure a unique name is used for its initialization. This is an IPC mechanism, so other processes will find it.
```
SetOnceNamedEvent event(L"unique_identifyier");
```
When something interesting happens and you want to let the world know about it, set the event:
```
bool ok = event.set();
```
That's it. From now on the variable is …
=> Abstraction on top of Win32 Named Events that can be set only once

.github/workflows/build-pr.yaml, .github/workflows/build-wsl.yaml
Due upstream issue introduced in the latest release (2.6.0).
See https://github.com/subosito/flutter-action/issues/179
=> Temporarily fix flutter-action version

wsl-builder/prepare-build/build.go
The WSL pipeline checksum file has more whistespaces between the fields.
`strings.Split` fails to produce the desired output: `Split: ["2f1e68d12994cb9c61085ea09720c7cef1728ca634ba9a447baa8a295499daf8" "" "ubuntu-kinetic-wsl-amd64-wsl.rootfs.manifest"]`
`strings.Fields` can treat multiple whitespaces as one, thus generating the expected length-2 slices.
=> Use strings.Fields to split the checksum file.

DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj, DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj.filters, DistroLauncher-Tests/DistroLauncher-Tests/upgrade_policy_tests.cpp, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/WSLInfo.cpp, DistroLauncher/WSLInfo.h, DistroLauncher/algorithms.h, DistroLauncher/stdafx.h, DistroLauncher/upgrade_policy.cpp, DistroLauncher/upgrade_policy.h
Currently only checking for UDI is relevant. Soon Subiquity-only will be as well, which will break the possibility of rendering a GUI from inside Linux, since there will be no GUI there anymore.
Thus, this pull request modifies the function that checks whether the distro is GUI-enabled to check for the existence of the UDI snap.
Since I wanted to reuse your implementation of `starts|ends_with` algorithms, I created a new header to host them (plus some other bits with similar scope).
=> Checks whether the rootfs has UDI or Subiquity snaps

DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj, DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj.filters, DistroLauncher-Tests/DistroLauncher-Tests/LauncherForceModeTests.cpp, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/LauncherForceMode.cpp, DistroLauncher/LauncherForceMode.h, DistroLauncher/OOBE.cpp, DistroLauncher/OOBE.h, DistroLauncher/WSLInfo.cpp, DistroLauncher/WSLInfo.h, DistroLauncher/installer_policy.h, DistroLauncher/stdafx.h
That variable is used to force a UI mode from the outside, before running the launcher. It's meant mainly for testability.
```cpp
///	0 or unset or invalid = autodetection
///	1 = text mode
///	2 = GUI mode.
```
It's use was located in the implementation of the function `mustRunOOBEinTextMode()` tightly coupled with detecting WSLg support. That function was in turn called by the `installer_policy.h` and the already dead `OOBESetup()` function.
The OOBE on Windows will have other requirements, but not WSLg, thus decoupling is necessary in order to preserve the env var semantics.
Thus, let's promote it to a "component" (its own thing) and decouple it from WSLg detection. The InstallerPolicy knows what to do if the variable is set or not, the same will be for the Windows OOBE application …
=> Models the environment variable LAUNCHER_FORCE_MODE

DistroLauncher/SetOnceNamedEvent.cpp
Calling SetEvent may return quickly enough so that the event HANDLE is closed without the other end receiving the notification.
SignalObjectAndWait let's us wait for the same event we are setting, so that we only proceed when the OS really delivered the notification.
=> Let SetOnceNamedEvent wait for confirmation

DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/DistroLauncher.vcxproj.filters, DistroLauncher/WinTuiStrategy.cpp, DistroLauncher/WinTuiStrategy.h
It is expected that UDI snap will be replaced by Subiquity only.
Thus GUI will only be supported if Flutter is supported on Windows.
Thus, for ARM64, only TUI will be possible.
Although we could add some checks to the existing NoSplashStrategy,
I'd rather keep them orthogonal as other differences may be detected later on.
The next step is the x64 strategy, which is more complicated, thus I preferred to push on a separate PR.
=> New app strategy for ARM64 in the context of the new OOBE

DistroLauncher/ApplicationStrategy.h, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/DistroLauncher.vcxproj.filters, DistroLauncher/WinOobeStrategy.cpp, DistroLauncher/WinOobeStrategy.h
Complementary to #254 , this PR implements the component will feed the Application class with the behavior necessary to run the OOBE on Windows. No dependency on WSLg. Requires x64 platform.
Choosing the app strategy now depends on:
- the platform set by the compiler
- the definition of WIN_OOBE_ENABLED constant (not yet defined anywhere, thus this won't affect 22.04.1 release).
Since the top-level `Application<>` class remains the same both the supported command line and its semantics must be preserved.
Terminal user interface support is still required because there are still situations only detectable during runtime that may prevent running the new OOBE, such as user disabling WSL2 localhost forwarding in `~\.wslconfig`. Achieving TUI support is very similar to what is done in …
=> Implements the WinOobeStrategy

DistroLauncher/WinOobeStrategy.cpp
In the reconfiguration worflow the OOBE must be able to start the Subiquity server as soon as possible. There is no need to wait for the registration event to be set. Setting it is harmless, but should not necessary. There was an issue in the OOBE, though, preventing it to start the server without the event being set. It's being adressed by: https://github.com/canonical/ubuntu-desktop-installer/pull/1035
=> No need for the registration event in reconfiguration workflow

DistroLauncher/WSLInfo.cpp, DistroLauncher/WSLInfo.h, DistroLauncher/WinOobeStrategy.cpp, DistroLauncher/algorithms.h
Here is the key of this PR:
```diff
// if none of the required snaps exist in the rootfs no UI will be available.
-        if (!internal::hasUdiSnap() && !internal::hasSubiquitySnap()) {
+        if (!internal::hasAnyOfSnaps(L"ubuntu-desktop-installer"sv, L"subiquity"sv)) {
```
For that to be possible, `hasAnyOfSnaps()` has to be implemented as a template function that can accept a variadic number of `string_view` arguments and applies the existing algorithms to find entries inside the snap directory matching one of the supplied arguments. Since that receives a variadic argument in order to nicely compose `find_file_if` and `std::any_of` we put together a `push_back_many` algorithm that populates a vector of string_views from a variadic argument list.
BTW, `find_file_if` returns a bool …
=> Traverse the filesystem only once when looking for UDI and Subiquity snaps.

DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj, DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj.filters, DistroLauncher-Tests/DistroLauncher-Tests/algorithms_tests.cpp, DistroLauncher/DistroLauncher.vcxproj.filters, DistroLauncher/WSLInfo.cpp, DistroLauncher/WSLInfo.h, DistroLauncher/algorithms.h, DistroLauncher/upgrade_policy.cpp
Removed the need to add braces around string literals in `starts_with` and `ends_with`:
```diff
- starts_with(string, { L"string_literal" });
+ starts_with(string,   L"string_literal"  );
```
The main issue is that `std::end(const char*)` points to the entry after the null termination, making naive implementations fail. This can be solved using string_views. Then template parameter deduction starts behaving funny. This is solved here with a helper adaptor template that does the following type conversions, in this order:
- `const CharT* -> basic_string_view<CharT>`: SFINAE'd to work only with chars. Null-termination expected.
- `const T[N] -> basic_string_view<T>`: SFINAE'd to work for non-characters only. No null-termination.
- `const T& -> const T&`: Any other containers stay as they …
=> Refactored starts_with and ends_with

.github/workflows/build-wsl.yaml
On top of the current practices of:
1. uploading some build artifacts during `build-wsl` CI workflow and
2. saving some metadata inside the repository wiki for further reuse during other runs of that workflow.
The proposed set of changes allows collecting program database files (.PDB) generated during compilation of the binaries bundled in the appx for easier crash analysis in the future.
PDBs are collected for each app built, always, and stored with a short retention policy (the same applied to the appx stored as part of the CI). Whenever those builds are pushed to the MS Store, their PDB's also go to the repository wiki as compressed tar balls, with the intent of allowing retrieving from the wiki the always up-to-date set of PDB's. 
Later, during a release, we can take those artifacts …
=> Upload program debug databases

DistroLauncher/upgrade_policy.cpp
At the eleventh hour we got this paramter wrong in the upgrade policy feature.
For example, a sample DistributionInfo.h from 22.04.1 contains the following:
```cpp
const std::wstring Name = L"Ubuntu-22.04";
// The title bar for the console window while the distribution is installing.
const std::wstring WindowTitle = L"Ubuntu 22.04.1 LTS";
```
The intended behavior cannot be achieved with `DistributionInfo::Name`, but with `DistributionInfo::WindowTitle` instead.
```cpp
if (starts_with(name, L"Ubuntu") && ends_with(name, L"LTS")) {
return L"never";
}
```
=> WindowTitle is the one which may have LTS in

meta/Ubuntu/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu/generated/store/en-us/ProductDescription.xml, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/Terminal/Fragments/terminal.json, meta/Ubuntu20.04LTS/generated/DistroLauncher/DistributionInfo.h, meta/Ubuntu20.04LTS/generated/store/en-us/ProductDescription.xml, wsl-builder/common/releasesinfo.go
Releases information fetched from Launchpad API during the CI workflows currently looks like:
```
ver.	m.	code	full version	Status				Activ.	Sup.	LTS		Opened			Release			Milestone
22.10    0    kinetic    Ubuntu 22.10    Active Development    True    False    False    2022-04-26            
22.04    1    jammy    Ubuntu 22.04.1 LTS    Current Stable Release    True    True    True    2021-10-15    2022-04-21    2022-08-11    2023-02-09
20.04    4    focal    Ubuntu 20.04.4 LTS    Supported    True    True    True    2019-02-18    2020-04-23    2022-02-24    2022-09-01
18.04    5    bionic    Ubuntu 18.04.5 LTS    Supported    True    True    True    2017-10-04    2018-04-26    2020-08-06    
16.04    6    xenial    Ubuntu 16.04.6 LTS    Supported    True    True    True    2015-10-19 …
```
=> Considers "Current Stable Release" as Supported for LTS's.

.github/workflows/build-pr.yaml, .github/workflows/build-wsl.yaml, DistroLauncher-Appx/Directory.build.props
The CI workflow is meant to provide the resources and execute the build system. Having it to know which Flutter project to builder (it could be either the current slide show or the new OOBE coming soon) and build it before invoking the actual build system that will output the appx bundle is a bad smell.
Instead we can let the build system (MSBuild) to handle building whatever dependencies the appx might have, only requiring the CI workflow to know that it must provide the Flutter command and that’s it.
This PR applies some renaming to turn it more subproject-agnostic in terms of whether we build the slide show or the OOBE application, as well as removing the build commands from CI workflow YAML files, leaving that to the actual build system (MSBuild) to handle.
=> Move the 'flutter build' commands from CI into MSBuild

DistroLauncher/DistroLauncher.cpp, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/stdafx.h, DistroLauncher/systemd_config.cpp, DistroLauncher/systemd_config.h
Co-authored by Edu Gómez Escandell <edu.gomez.escandell@canonical.com>
https://ubuntu.com/blog/ubuntu-wsl-enable-systemd
=> Enables systemd by default on Ubuntu Preview

DistroLauncher/SetOnceNamedEvent.cpp, DistroLauncher/SetOnceNamedEvent.h
We previously tracked whether the event was set or not by assigning `nullptr` and to avoid leaks we close the handle right after setting it.
To preserve the semantics of being able to set it only once, we now track the set state using a boolean.
Deferring closing the handle to the destructor of this object allows for an OOBE GUI late in the initialization process to still find the event already set. Otherwise, closing the handle much earlier than any client would be able to check it, would allow the kernel to destroy the object.
This was never an issue because the OOBE inits very fast. But with the upcoming end to end test this would be a major block: the launcher would never be effective in communicating the registration completion event.
=> Closes the handle only at destructor

DistroLauncher/WinOobeStrategy.cpp
TUI currently does that internally (via its installer policy), so no need to touch just now. When the Win32 Flutter OOBE gets ported to Jammy we need to revisit this topic since the TUI routine will be drastically simplified.
I guess this was a kind of leftover between rebases. The function (`serverExitStatusCheck()`) was there, but never called.
=> Ensures serverExitStatusCheck is called for the gui setup

DistroLauncher/ChildProcess.cpp
This doesn't seem useful if the child is a window application. But showed useful when dealing with the PoC e2e test.
This approach is quite controversial though. See the following links for the downside of doing such.
https://devblogs.microsoft.com/oldnewthing/20100325-00/?p=14493
https://devblogs.microsoft.com/oldnewthing/20100326-00/?p=14483
Still seems as harmful as doing nothing (the previous behavior) for GUI child processes.
=> Ensures the child process has at least one thread available for input

.github/workflows/build-pr.yaml, .github/workflows/build-wsl.yaml
There was a breaking change in the package `flutter_html` that motivated the `ubuntu_desktop_installer` to pin a very specific version of that package. See https://github.com/canonical/ubuntu-desktop-installer/pull/1152. That is the reason for the current break in our CI build. Thus, we need to update the UDI submodule. 
I also took the freedom to unpin the flutter-action version from our CI.
[This run](https://github.com/ubuntu/WSL/actions/runs/3184611222) proves this work.
=> Fix flutter build CI

meta/UbuntuPreview/generated/DistroLauncher-Appx/Directory.build.props, meta/UbuntuPreview/src/DistroLauncher-Appx/Directory.build.props
Enables the CI to inject the Go stub when running the e2e tests.
By default it does nothing.
For now that's only possible for Ubuntu-Preview, thus it goes into `meta` directory. Once Jammy gets the new OOBE backported, that will be the default behavior.
=> Imports ui-driver.props if exists.

e2e/test-runner/wsl_tester.go
Three changes I made for debugging that I thought would be useful in general, each corresponds to a commit, in order:
1. When an Os comand assertion fails: It prints command + arguments instead of only printing the command (which is most often going to be either `powershell.exe` or `wsl.exe`).
2. When any of the logs cannot be accessed: Do not print it as a failed assertion but rather say that the log could not be found.
3. When the client logs cannot be found: Use `Logf` instead of `Fatalf` so that unregistering is not skipped.
4. Last commit simply adds a couple of line breaks so the new output it is a bit more readbale.
```
PS> go test .\test-runner\
--- FAIL: TestBasicSetup (3.61s)
wsl_tester.go:80: Failed to run the command: powershell.exe. Error exit status 1
wsl_tester.go:39:
=== …
```
=> Printing more info when E2E tests fail

.github/workflows/build-pr.yaml
Due that being moved to WSL pipeline.
Later we'd address the build-wsl workflow.  That's slightly more complex. This one is very straightforward and blocks other pull requests.
=> Updates the link to jammy rootfs

e2e/test-runner/wsl_tester.go
I continue my quest to improve the test debugging experience.
This time, I added the result of the failed command to the output:
```diff
=== RUN   TestBasicSetup
wsl_tester.go:87: Failed to run command:
> wsl.exe -d UbuntuDev.WslID.Dev systemctl is-system-running
Error: exit status 127
+       Output: /bin/bash: line 1: systemctl is-system-running: command not found
wsl_tester.go:40: 
=== Server Debug Log ====
[...]
```
=> [e2e] More info printed on error

e2e/test-runner/wsl_tester.go
When a test fails early during installation, the symlink to the ubuntu-desktop-installer logs points to the previous test's log. This can be confusing.
This PR erases the symlink (not the log itself) during setup.
=> e2e: Removing old log before running tests

e2e/pre-e2e-testing.ps1
This PR adds a script to be invoked either locally or via CI to build the end-to-end testing enabled application package bundle.
I'd love to receive a recommendation for a better way to `FailFast`. That looks ugly to me, but Powershell is not on my skillset. 😅 
To test it locally, run from the repository root:
> ### I'd really appreciate if you guys could do some local tests before approving this.
```
.\e2e\pre-e2e-testing.ps1 -AppID "UbuntuPreview" -RootfsX64 <rootfs_URL> -CertificateThumbprint <your_pfx_thumbprint>
$env:LAUNCHER_REPO_ROOT=$(pwd).Path
cd .\e2e
go test .\test-runner --distro-name Ubuntu-Preview --launcher-name ubuntupreview.exe
```
Rootfs URL can be a local path.
My reasoning was that we will more often touch the interpreted code (`test-runner` Go module and the Flutter …
=> End-to-end testing bed preparation script

e2e/test-runner/go.mod, e2e/test-runner/runner_test.go
The launcher modifies some config files in WSL. These tests verify this happens.
Feature commits:
- [96dc60f](https://github.com/ubuntu/WSL/pull/292/commits/96dc60fed90c6e378b7a75c28bef92b7b8a8c180) tests that systemd is enabled and that the fixes the launcher applies to to sysusers service work.
- [8acfd93](https://github.com/ubuntu/WSL/pull/292/commits/8acfd9380b3c1698bbf99fa154d86940e15e11ae) tests that the upgrade policy is set according to the distro name
- [5f1d754](https://github.com/ubuntu/WSL/pull/292/commits/5f1d754a91c292480008406d5571fabb2ef7befc) tests that we used the right rootfs link. This test will have to be updated every time there is new release. I didn't want to automate it because the point of this test is to test this very automation.
Cleanup commits:
- …
=> Adding e2e testing relating to config 

e2e/test-runner/default_experience_test.go, e2e/test-runner/runner_test.go, e2e/test-runner/wsl_tester.go
`launcher.exe --hide-console` is the command line used by the Start Menu and by the Store app installer to invoke the distro launcher. That is most likely the preferred way users interact with the distro launcher during the initial setup. When the setup is complete the launcher runs the shell, which depends on user interaction to exit.
In order to mimick this, we launch the aforementioned command in a forked process and monitor it from the original process by capturing its StdErr, StdOut and the distro status as shown by `wsl -l -v`. Note that I have not found a way to capture the text written to console by WSL's interactive session, as it is sent neither to StdOut nor StdErr.
*Result*:  WSL knows it's not running in a terminal and hence does not run the same way. For instance, it's not …
=> Adding test to validate most common installation procedure

DistroLauncher-Appx/Directory.build.props
The failure was a very strange complain about not being able to merge a resource.pri file from some inner asset package of the bundle.
```
Merge failure for shared merged PRI file: error 0x80070490: no se puede registrar el paquete CanonicalGroupLimited.Ubuntu_2204.1.9999.0_x64__79rhkp1fndgsc porque 
hubo un error de combinación con el siguiente archivo: C:\Program
Files\WindowsApps\CanonicalGroupLimited.Ubuntu_2204.1.9999.0_neutral_split.scale-150_79rhkp1fndgsc\resources.pri
```
Removing the conditional inclusion of the Flutter app prevented the error (making it unconditionally being included for both architectures, even though it won't run on ARM64). The relationship between the problem and the fix is not apparent. Also, the Ubuntu-Preview has the same conditional but installs …
=> Prevents Ubuntu and Ubuntu-22.04 installation problem

DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj, DistroLauncher-Tests/DistroLauncher-Tests/DistroLauncher-Tests.vcxproj.filters, DistroLauncher/Application.h, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/snapd.cpp, DistroLauncher/snapd.h
We found out during development of the end-to-end test CI workflow that if enough time elapsed between enabling systemd in the `/etc/wsl.conf` file and actually running the OOBE, the distro would restart with systemd as PID 1, snapd service would try to run, but because the current version shipped with the Kinetic's rootfs is broken for WSL (v2.57.4), it left the distro filesystem in a bad state where the snaps we need to run the OOBE becomes not found on the expected directory.
That behavior was not easily discoverable through other kinds of tests, because it seems almost impossible to have enough time between enabling systemd and running the OOBE in production. I wonder if a much slower host computer would behave similar to the end-to-end test, but I still don't know at this point.
This …
=> Disables snapd v2.57.4 before running the OOBE

e2e/test-runner/runner_test.go
The subiquity snap doesn't supply the language-selector-common package, required for finding which language packs must be installed for better user experience with translations.
We need to seed that package into our rootfs and update the configure controller to look for it in the base system (outside of the snap) or find other ways, since the easy path - adding the package to the snap - was refused.
Fixing the actual issue is a bit out of the scope of the current PR because we urge to make the CI workflow ready. The real fix will come later.
=> Disables the assertion about language packs

DistroLauncher/ChildProcess.cpp
The wait introduced in https://github.com/ubuntu/WSL/pull/278 broke the communication between the splash app (the slide show only) and launcher. The splash communicates its HWND on creation, through a named pipe created by the launcher. The wait caused the splash window to try to communicate before the named pipe was created. That wait is only useful if the child is a console app (the case for E2E). Thus, the appConfig check makes sense.
In the certainty that we will soon backport the OOBE on Windows to Jammy and thus deprecate the slide-show-only splash application, a more robust fix would be an overkill.
=> Addresses loss of comm between splash and launcher

DistroLauncher/WinOobeStrategy.cpp
In https://github.com/ubuntu/WSL/pull/297#issuecomment-1289899832 it was mentioned that CI started to present failures very often due launcher failing to write the prefill file.
This PR aims to address that condition by running a command through WSL API to make sure the distro is awakened before attempting to write the prefill file. Two successful runs in a row ( [this](https://github.com/ubuntu/WSL/actions/runs/3324081695) and [and this one](https://github.com/ubuntu/WSL/actions/runs/3324295570)  ) seem to confirm the suspicious is right.
=> Fix CI failure due prefill file not found

DistroLauncher-Appx/MyDistro.appxmanifest, DistroLauncher/Application.h, meta/Ubuntu/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu22.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/UbuntuPreview/generated/DistroLauncher-Appx/Directory.build.props, meta/UbuntuPreview/src/DistroLauncher-Appx/Directory.build.props, meta/UbuntuPreview/src/DistroLauncher-Appx/MyDistro.appxmanifest
My original intent to implement this was to adjust only the appxmanifest files. But then I got a question: is `wsl --install` supposed to execute the appxmanifest entry point or invoke the distro launcher directly (most likely with no arguments)? I don't really know the answer, but I suspect it is the latest and that requires consistency between that behavior and installation through the store.
Thus, in the following set of changes I'm preparing both scenarios:
1. The one-line change in the `DistroLauncher-Appx/MyDistro.appxmanifest` makes the entry point for all apps to be `<launcher.exe> --ui=none`, thus following the upstream setup experience (the one existing in Ubuntu 18.04 and 20.04 - prior to the Ubuntu OOBE) [d08bdc84135e0c3b8a7b5f8f24cc5d2b48de558a]
2. The same change is applied …
=> Default setup experience to bypass Ubuntu OOBE

DistroLauncher/DistroLauncher.cpp, DistroLauncher/systemd_config.cpp, DistroLauncher/systemd_config.h
The service `systemd-sysusers` fails at startup when trying to load credentials. To fix this, we overrode its conf file in `/etc/systemd/system/sytemd-sysusers.d/override.conf` in UbuntuPreview.
This patch enables this fix in all distros. Note that systemd is still only enabled by default on Preview and Dev.
The function `Systemd::Enable` has been renamed to `Systemd::Configure` to reflect the fact that it permorms this action even when systemd is not enabled.
=> Backporting systemd-sysusers.service fix to older distros

DistroLauncher/WSLInfo.cpp
As per the documentation in https://learn.microsoft.com/en-us/windows/win32/api/wslapi/nf-wslapi-wslgetdistributionconfiguration#remarks
> The caller is responsible for freeing each string in pDefaultEnvironmentVariablesArray (and the array itself) via CoTaskMemFree.
Emphasis on "and the array itself".
=> Fixed memory leak in WslGetDistributionConfiguration

.github/workflows/e2e.yaml
We need to run apt update before running apt install in CI.
This should be picked in the new test workflow branch (with the `DEBIAN_FRONTEND=noninteractive` change too that I ignored here to avoid mix of concerns)
=> Run update before installing in CI

DistroLauncher/DistroLauncher.cpp
Refresh releases and assets is an automated action that looks for the string "UbuntuDev.WslID.Dev". If this string is found, then multiple copies of the file are generated in which this string is replaced with "Ubuntu-18.08", "Ubuntu-20.04", etc. To avoid triggering this, I changed the code so it does not contain string "UbuntuDev.WslID.Dev".
You can see an undesired trigger here: https://github.com/ubuntu/WSL/pull/290
=> Avoid triggering Refresh releases and assets

DistroLauncher/systemd_config.cpp, e2e/launchertester/basic_setup_test.go, e2e/launchertester/default_experience_test.go, e2e/launchertester/test_cases.go
Disables systemd-binfmt.service to avoid breaking interop. This is a temporary solution, as we're still vulnerable to other distros breaking interop.
Fixes https://github.com/ubuntu/WSL/issues/334
=> [DEENG-544] Disable systemd-binfmt.service

DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu22.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest
To support Windows Server, we cannot rely on the store to deliver VClibs.
The launcher vcxproj is already configured the way we want. The Flutter binaries are now, since #338 and #339 .
=> Removes the `PackageDependency` entry from manifest

README.md
Until now we had the same README as the reference implementation. This made staying is sync with upstream simpler. However, the added cost of having our own readme seems worth it to avoid causing confusion, so we've decided to write our own.
closes #329
=> [WSL-354] Creating README.md

.github/actions/wsl-bash/action.yaml, .github/actions/wsl-checkout/action.yaml, .github/actions/wsl-install/action.yaml
Internal imports need to be absolute for external repositories to be able to use them.
Follow-up to #337.
=> Fixed internal imports in actions

wsl-builder/prepare-build/buildGHMatrix.go
Previously only Kinetic was published on WSL pipeline. Jammy has also been ported.
This PR changes the URL generation in `wsl-builder/prepare-build` to acknowledge the new rootfs location.
That's the reason why the CI is failing to build the 22.04 LTS app.
=> Updates rootfs URL generation for Jammy

.github/workflows/build-wsl.yaml
Basic GitHub actions mistake. 🙈 
We are attempting to store the debug symbols of the latest published apps in the wiki.
For that we need to know whether this build lead to a new submission to the store: `steps.detect-upload-to-store.outputs.needs-upload`.
The problem is that we were attempting to read the output of a step that belongs to another job. That can only work if the job who owns that step makes the output available.
=> (fix) Cannot read output from previous job steps

.github/actions/wsl-install/action.yaml
WSL-449
That value is winget's exit code when no updates are available to install. That means we have the latest and greatest installed. No reason for immediate crashing.
That error code might mean a real failure, though. Thus as an extra precaution we launch wsl --version and check.
See
https://github.com/microsoft/winget-cli/blob/bfcee8edba2853f5a11e96dd7c7f6b412afef26a/src/AppInstallerSharedLib/Public/AppInstallerErrors.h#L58
And
https://github.com/microsoft/winget-cli/blob/bfcee8edba2853f5a11e96dd7c7f6b412afef26a/src/AppInstallerCLICore/Workflows/UpdateFlow.cpp#L67
=> Having no updates to install should not break CI

DistroLauncher/DistroLauncher.cpp
After building an appx with current jammy rootfs, the result should look like:
```
$> ubuntu2204.exe   
Installing, this may take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: u
New password:
Retype new password:
passwd: password updated successfully
The operation completed successfully.
Installation successful!
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.90.1-microsoft-standard-WSL2 x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
This …
```
=> Enable systemd by default on Ubuntu and Ubuntu-22.04 apps

DistroLauncher-Appx/MyDistro.appxmanifest, DistroLauncher/Application.h, meta/Ubuntu/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest, meta/Ubuntu22.04LTS/generated/DistroLauncher-Appx/MyDistro.appxmanifest
Deploying Ubuntu 22.04 to Windows Server 2019 fails due what seems to be an invalid `AppxManifest.xml`. The truth behind that message is that the namespace `http://schemas.microsoft.com/appx/manifest/uap/windows10/10` is not supported on that OS version.
We only used that namespace to pass command line parameters to the application.
This PR:
1. changes the CLI parsing to ensure the previously desired behavior is now matched when no CLI parameters are passed 
2. Removes the dependency on that namespace from the `MyDistro.appxmanifest` of all LTSs and the main Ubuntu app.
3. Preserves the above dependency for the Ubuntu Preview application.
The point 3 ensures that Ubuntu Preview invokes the OOBE by default. That behavior is being herein preserved under the assumption that the users willing …
=> Removes the dependency on the UAP10 namespace

.github/workflows/e2e.yaml
This PR addresses further issues with CI end-to-end tests:
1. `FlutterGuardedError` spuriously appearing. Recently became really recurrent. Partially addressed in https://github.com/canonical/ubuntu-desktop-installer/pull/1887.
2. Ensures the submodules are recursively updated for the end-to-end tests. The other workflows where this might be relevant update the submodules via git CLI.
While investigating 1 I noticed leftovers not being updated/removed from the UDI submodule. I suppose those leftovers are somehow related with the higher frequency the CI failed the past three days.
=> Fixes for `FlutterGuardedError` seen in CI

DistroLauncher/ApplyConfigPatches.cpp, DistroLauncher/ApplyConfigPatches.h, DistroLauncher/DistroLauncher.cpp, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/Patch.h, DistroLauncher/stdafx.h
A top-level function called from `InstallDistribution()` (see `DistroLauncher.cpp`). Calling at this place we can ensure we have the necessary file system permissions to perform any config patch.
Calls patches in two steps: globals and release specific.
The patch collections are defined, but empty for now. Thus, for now this does nothing.
The collections will be populated as we add specific patches at next.
Nothing will change on this function or its caller as we add more patches.
=> Applies all relevant patches to the distro being installed

DistroLauncher-Tests/DistroLauncher-Tests/PatchTests.cpp, DistroLauncher-Tests/DistroLauncher-Tests/algorithms_tests.cpp, DistroLauncher/Patch.cpp, DistroLauncher/Patch.h, DistroLauncher/algorithms.h
A patching function is implemented and registered for all distros to remove all lines from `/etc/fstab` which start with `LABEL=cloudimg-rootfs`.
The existence of that line causes the `systemd-remount-fs.service` to fail. That's been observed on 20.04 but might happen to any distro.
Builds on top of the Patcher machinery presented in #368 .
Now it becomes easy to understand how that whole thing pays off (IMHO).
=> Removes `cloudimg-rootfs` label from all distros fstab's

DistroLauncher-Tests/DistroLauncher-Tests/PatchTests.cpp, DistroLauncher/Patch.cpp, DistroLauncher/Patch.h
Implements a patching function to write overrides to units preventing them to start on containers. Such as WSL distro instances.
That function is registered for `systemd-modules-load.service` on 18.04. Other releases already have that condition on the system unit file shipped with the distro rootfs.
=> Fix  `systemd-modules-load.service` on 18.04 via `ConditionVirtualization` for units

DistroLauncher-Tests/DistroLauncher-Tests/PatchTests.cpp, DistroLauncher/Patch.h
By reusing `OverrideUnitVirtualizationContainer()` supplied in #371 but registering it to write an override for `multipathd.socket`.
When enabling systemd on Ubuntu 20.04, `multipathd.service` reports failure because of the socket. The service itself has the `ConditionVirtualization` on the unit file, but the socket doesn't. Something else might be trying to talk through that socket, causing systemd to try to start it and fail. Only 20.04 was observed with that behavior.
Before:
After:
=> Disables `multipathd.socket` on Ubuntu-20.04

.github/workflows/build-pr.yaml, .github/workflows/build-wsl.yaml, .github/workflows/e2e.yaml, e2e/launchertester/test_cases.go
Aligned with UDI, because some dependencies are broken with Flutter 3.10 (just released).
Also, CI expected Ubuntu-Preview to be Lunar, but we are now at Mantic.
Having two unrelated fixes together is the only way to see the CI checks all going green :)
=> (fix): Pin Flutter Version in CI

DistroLauncher/Patch.cpp, DistroLauncher/Patch.h
Focal is shipped with OpenSSH server, whose systemd service fails to start because the setup process doesn’t setup the host key. This short-term solution disables the service, and the long-term solution will be to remove the openssh package from the seed.
UDENG-286
=> Disable SSHD service in Ubuntu 20.04

.github/workflows/build-wsl.yaml
We're trying to debug why recent builds did not result in isotracker notifications. This will give a bit more context at least.
=> Add debugging info display to the notify-isotracker github action.

.github/workflows/build-pr.yaml, .github/workflows/build-wsl.yaml, .github/workflows/e2e.yaml
We need the `ubuntu_logger` updates and Flutter 3.10 to allow the build workflow to succeed.
Details in:
https://github.com/canonical/ubuntu-desktop-installer/commit/62a5ead0c592cd77a2876e9634b9fa73dc9c94e6
https://github.com/canonical/ubuntu-flutter-plugins/commit/6d74e3d5699e5b31b1fd56983b71ff01ff2ac625
=> chore: Update UDI Submodule and Flutter SDK

.github/actions/wsl-install/action.yaml
This'll fold Winget's output, which is needlessly long with its progress bar and all.
=> Gardening 🌱: Hide Winget's loooong output behind a log group

DistroLauncher/ConfigRootFs.cpp, DistroLauncher/ConfigRootFs.h, DistroLauncher/DistroLauncher.cpp, DistroLauncher/DistroLauncher.vcxproj, DistroLauncher/Patch.cpp, DistroLauncher/Patch.h, DistroLauncher/stdafx.h
After a team discussion we concluded that the way we closed #382 was inappropriate (thus this PR reverts it) and we should disable the SSH `systemd` unit via `systemctl disable`.
That cannot be made into the existing patching feature.
So I took the simplest approach of just running the command explicitly, but I placed the code where it's easily amendable to a more involved solution, if we start to mix and match different releases and `systemd` units to disable and require something similar to the patching feature into selecting the units per release and forming the `systemctl`command line accordingly. For now that would be an overkill since we only have one `systemd` unit and one release to match.
---
The result of a sideload installation of 20.04 after this looks like the following:
``` …
```
=> fix: Disable SSH unit on 20.04 via `systemctl disable`

.github/actions/wsl-install/action.yaml
For some reason these if-checks are not working adequately, so instead I opt for a ask-for-forgiveness rather than ask-for-permission approach.
You can see the leftover distros interfering here: https://github.com/ubuntu/WSL/actions/runs/5118578090/jobs/9202785080?pr=397
=> Simplify cleanup of leftover distros in wsl-install action

.github/actions/wsl-checkout/action.yaml
Apparently you cannot fetch the branch you're in. This is not an issue when this action is called in a PR:
- `git clone ...` clones into main
- `git fetch ...` fetches the PR ref
However, when this action is ran on main (for instance, after merging the PR), the fetch will try to fetch main, and fail.
See here:
https://github.com/ubuntu/wsl-actions-example/actions/runs/5120947427/jobs/9208564434
See a Stackoverflow thread about this:
https://stackoverflow.com/questions/2236743/git-refusing-to-fetch-into-current-branch
=> Fix obscure Git error in wsl-checkout

.github/workflows/update-rootfs-cache.yaml
It was using an action that has not existed for a while
=> Fix update-cache

.github/actions/download-rootfs/action.yaml, .github/workflows/update-rootfs-cache.yaml
Since Powershell 6+ invoke-Webrequest has a retry option. Use this option in case of failure together with the resume option.
Besides, the path to action.yaml was wrong.
UDENG-1813
=> ci: retry rootfs download if it fails

e2e/launchertester/test_cases.go
quick'n dirty fix to the version. Ideally we use something similar to distro-info but since it's running on Windows it is not so straightforward.
=> tests: fix version of the devel release

e2e/launchertester/basic_setup_test.go, e2e/launchertester/default_experience_test.go, e2e/launchertester/test_cases.go
We deemed that manually updating this every now and then is not worth the effort.
---
UDENG-1816
=> fix(e2e): Remove testCorrectReleaseRootfs test case

DistroLauncher/DistroLauncher.cpp, DistroLauncher/messages.mc, e2e/go.work, e2e/launchertester/basic_setup_test.go, e2e/launchertester/help_test.go, e2e/launchertester/test_cases.go
The way command line arguments are parsed is not ideal, but that is mostly inherited from upstream.
Command `launcher.exe help` should print the help and exit, however `help` is not a real command, so it defaults to the same behaviour as `launcher.exe made-up-command`. It first installs and then fails to launch.
I fix this by checking for `help` very early on.
UDENG-276
=> Fix help argument to not install the distro

.github/workflows/build-wsl.yaml
We are going to manually build special images of WSL, disable automated builds to be in control of what and when we deliver. This will be reenable gradually post 24.04 LTS release.
=> maint: disable automated build

.github/actions/wsl-bash/action.yaml
The /tmp directory is, as expected, temporary. This is broken with regular WSL (files persist), which is something we were using in this action.
However, enabling systemd makes it so the contents of /tmp  are no longer persistent.
---
This is being tested here:
https://github.com/ubuntu/wsl-actions-example/pull/6 (cloud-init workflow)
=> fix(actions/wsl-bash): Bash-WSL action: write temp script in the Windows filesystem

docs/.custom_wordlist.txt, docs/custom_conf.py, docs/reference/distributions.md, docs/tutorials/cloud-init.md, docs/tutorials/index.md
This PR adds a tutorial for auto setup an UbuntuPreview instance with cloud-init.
It assumes things that are not yet true, so we should not merge it right away:
1. WSL datasource in cloud-init (and its reference documentation) is merged. Not yet, see PR https://github.com/canonical/cloud-init/pull/4786
2. UbuntuPreview app comes with cloud-init by default - not yet seeded
3. Subiquty is removed - also not yet.
Once allfacts above are true, this tutorial will be valid.
Yet, assuming one can prepare an Ubuntu WSL image (doesn't have to be Noble BTW) with cloud-init seeded and modified to add the WSL datasource above mentioned, the subsequent steps are valid and can be followed to setup an instance with minimal touch.
I'm doing exactly that all the time for a few days for testing (and …
=> feat(docs): Tutorial for auto setup with cloud-init

build-remote, wsl-builder/common/releasesinfo.go
We now have per appid livebuild produced rootfs. Adjust the paths to download them generically.
=> Download rootfses specific to appid livebuild rootfs

.github/workflows/build-wsl.yaml
Separate upload to the Store from storing the new version so that even manual build can be uploaded to the Store.
UDENG-2387
=> CI: Always store the new build-id

docs/tutorials/interop.md
From the bug report:
> I really appreciate the content y'all have added on working with Ubuntu and WSL! I have been making it up as I go along and I've cobbled together some patterns that work okay but I've learned a lot from these tutorials that I couldn't suss out on my own.
> 
> I just wanted to point out that there's a bug in the python code below the line "Copy this to the first cell, adapting the input directory:"
> 
> The screenshot has correctly-indented code, but the copy-able code in the code block mistakenly indents these two lines:
> ```
>       data[mime_type] += 1
>       csv_cols = ["mime_type", "count"]
> ```
> This leads to counting every mime_type exactly once. This has an impact later-on when the aggregate data is then filtered by frequency; every mime_type is filtered …
=> Fix python script in interop.md, fixes #443

.github/workflows/build-wsl.yaml, wsl-builder/common/releasesinfo.go
* Adapt RootfsURL to current cloud-images
Adapt it to our current cloud-images copy work, which strips the "ubuntu" prefix and replace it with "wsl" when the appid is empty.
Support older versions too.
* Reenable automated build cron job
UDENG-2573
=> maint: allow download from cloud image and reenable automated build

build-remote
LP API distro collections now returns from most recent to oldest. This is the iteration over the collection directly, so only assign it if it’s not assigned.
=> build: fix latest LTS detection

docs/.custom_wordlist.txt, docs/tutorials/dotnet-systemd.md
The dotnet-systemd tutorial had some issues that could block a user from completing its steps.
Some of the major ones included:
- Using the latest LTS (24.04) .NET 6 could not be installed using the command indicated in the tutorial
- Instructions for setting paths in the config for the systemd service were not sufficiently clear and deviated slightly from the main text
- Distinct CLI commands were erroneously concatenated on a single line
- There was a typo in a method call that the user needed to insert in a file to run the systemd service successfully
- A placeholder referred to a minimum WSL version necessary to leverage systemd but no version was cited
In addition to these changes, a number of minor improvements were made,
primarily relating to clarification of text and removing …
=> Rework dotnet systemd tutorial

docs/.custom_wordlist.txt, docs/explanations/index.md, docs/explanations/up4w.md, docs/index.md
This PR rewrites the Ubuntu WSL docs homepage to achieve the following goals:
- Impose standard homepage structure for Canonical docs
- Increase focus on Ubuntu WSL rather than (Microsoft) WSL
- Highlight material that is covered elsewhere in the docs
- Include reference to Ubuntu Pro for WSL (UP4W) and a short explanatory note for UP4W in the docs
For reference, this aims to satisfy some of the following features of a homepage:
1. A single sentence that says what the product is, succinctly and memorably
2. A paragraph that describe what the product does.
3. A third paragraph explaining what need the product meets.
4. A paragraph that describes whom the product is useful for.
5. A grid of links to relevant Diataxis sections with short descriptions
Nick Veitch (Canonical) provided feedback …
=> Rewrite homepage in standard form

.github/workflows/e2e.yaml, CONTRIBUTING.md, docs/.custom_wordlist.txt, docs/guides/contributing.md, docs/guides/index.md, docs/index.md
This adds contribution guidelines in the following way:
- `CONTRIBUTIONS.md` added to root of repo
- Content from `CONTRIBUTIONS.md` included in `docs/guides/contributing.md`
- Reference to `docs/guides/contributing.md` added to homepage
- Links relevant to contributing added to homepage
- Additional minor changes (e.g., modified custom wordlist)
Note, the contributing guidelines refer to both Ubuntu WSL and Ubuntu Pro for WSL, due to the expected merging of these doc sets.
Some technical input might be needed for material relating to how contributors can contribute to the Ubuntu WSL code base specifically.
UDENG-3268
=> docs: Add contributing docs

CONTRIBUTING.md, docs/custom_conf.py, docs/guides/install-ubuntu-wsl2.md, docs/tutorials/cloud-init.md, docs/tutorials/data-science-and-engineering.md, docs/tutorials/dotnet-systemd.md, docs/tutorials/gpu-cuda.md, docs/tutorials/interop.md, docs/tutorials/vscode.md
This PR improves the consistency and functionality of code blocks in the docs.
The main changes are:
- Addition of a CSS selector that allows copy buttons to be deactivated in code-blocks. This is especially useful for code blocks that contain output.
A code block with the regular behaviour is written:
\```{code-block) text
PS C:\Users\myuser> echo $env:USERPROFILE
\```
Result (note the button on cursor hover): 
If we do not want the copy button, we write:
\```{code-block) text
:class: no-copy
C:\Users\myuser
\```
Result (note the lack of button on cursor hover):
- Addition of regex-based solution to prevent copy/pasting of command prompts. This ensures that the prompt and any text preceding the prompt is not copied when a user clicks the copy button. This is done automatically for any …
=> docs: Improve code blocks

docs/.sphinx/get_vale_conf.py
Updates the configuration settings for the [Vale](https://vale.sh/) linter, based on recent changes to the docs Starter Pack.
Vale can now be invoked successfully with `make vale`, which will generate errors, warnings and suggestions based on documentation style.
UDENG-3785
=> docs: Add check for vocab files to Vale config

docs/guides/install-ubuntu-wsl2.md, docs/tutorials/data-science-and-engineering.md, docs/tutorials/dotnet-systemd.md, docs/tutorials/gpu-cuda.md, docs/tutorials/interop.md, docs/tutorials/vscode.md
Images previously had no alt text, which is an accessibility issue.
This adds alt text to all images in the documentation.
Special thanks to @davidekete for collaborating with the Ubuntu WSL team through the Canonical Documentation Academy and writing appropriate and effective alt the text for the images.
[See the original Open Documentation Academy PR here.](https://github.com/canonical/open-documentation-academy/pull/124)
UDENG-3784
=> docs: Add alt text for images

docs/.custom_wordlist.txt, docs/guides/install-ubuntu-wsl2.md
This removes the winget method from the installation instructions because it is not currently well-supported.
It is replaced by a section on installing without the Microsoft Store, as this is important to some users.
However, it is made clear that we do not currently recommend a specific store from which to download images.
A brief section on running an instance of Ubuntu was also updated, as it was previously tied to the winget section and did not use the latest LTS.
UDENG-4097
=> docs: update installation methods

e2e/launchertester/basic_setup_test.go, e2e/launchertester/test_cases.go
As a part of cross-distro effort, we are trying to make sure that snapd works well in WSL environments. We now have WSL-specific release tests that check new snapd releases in Ubuntu 22.04 and Ubuntu 24.04 as running inside WSL. We want to complement this with a small smoke test that ensures subsequent WSL releases do not regress running snapd.
The test itself installs the hello snap from the store and runs it.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-24157
=> e2e: add smoke test for running snaps

.github/workflows/build-pr.yaml, .github/workflows/build-wsl.yaml
v1 and v2 are deprecated, v3 deprecation is near.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
For the current purposes of this repository the v4 can be considered a drop-in replacement.
=> Upgrades up(down)load-artifact actions

CONTRIBUTING.md, docs/index.md, docs/tutorials/cloud-init.md
With that release comes changes to the distro launcher making it no longer necessary for users to run cloud-init commands. The distro launcher does it, so the tutorial can be made shorter and more direct.
Also there was a caveat about `wsl --install` that's no longer applicable, as that installation command also goes through the launcher, both workflows are now consistent.
=> docs: Update cloud-init tutorial for 24.04.1

docs/custom_conf.py, docs/guides/autoinstall.md, docs/guides/index.md
This removes documentation of the autoinstall feature (deprecated) and redirects the old url for autoinstall to the cloud-init doc. Follow up to discussion in #500 .
=> docs: Remove autoinstall doc

SECURITY.md
Adds `SECURITY.md` file to root of repo.
UDENG-5433
=> docs: add security policy file

.github/actions/download-rootfs/action.yaml, .github/actions/download-rootfs/download-rootfs.ps1, .github/workflows/build-pr.yaml, DistroLauncher/Ubuntu/InitTasks.cpp, e2e/go.work, e2e/launchertester/basic_setup_test.go, e2e/launchertester/go.mod, e2e/launchertester/test_cases.go, e2e/launchertester/testdata/TestSetupWithCloudInit/do_not_block_on_wsl1, wsl-builder/common/releasesinfo.go
`cloud-init status --wait` blocks forever if cloud-init won't ever start. Known cases where that may happen:
1. the cloud-init systemd units being masked or disabled by default in the rootfs (not our case)
1. systemd not enabled by default in the rootfs image (not our case either)
1. the distro instance being registered as a WSL 1 instance (we don't control that :) )
We're not considering that properly. With the patch https://github.com/ubuntu/WSL/pull/508/commits/bb7265201cb521ec23a636e4d7f221376880eb4c, we check if both the cloud-init.service unit is enabled (which covers 1) as well as systemd not offline, which covers 2. and 3.
The very same check was implemented in the new script that will replace this launch in the new WSL format via this PR: …
=> Fix cloud-init blocking on WSL1
