.github/workflows/build-wsl.yaml
Do not rely on inputs parameters for updating db and printing notice as daily build don’t have any.
=> Fix update db

.github/workflows/build-wsl.yaml, DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, DistroLauncher/OOBE.cpp, meta/Ubuntu/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/Ubuntu20.04LTS/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/Ubuntu22.04LTS/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj, meta/UbuntuPreview/generated/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj
* Fix build system for good this time, by checkouting correct sha.
* Add sudo to start wsl-setup as it’s expected to be ran as in a SUDO environment.
* Readd some dll that were not shipped due to edited master file (+ revert generation). However, some dlls are still missing…
=> Fix launching u-d-i

DistroLauncher-Appx/DistroLauncher-Appx.vcxproj
When I did the same for the vcxproj files I created a mismatch that is triggering the CI to auto pull request downwards.
This aims to fix the issue triggering the CI.
=> Bumping SDK version on the Appx vcxproj file.

meta/Ubuntu/src/store/en-us/ProductDescription.xml, meta/UbuntuPreview/src/store/en-us/ProductDescription.xml
Updated the descriptions for all the products with the difference
between versioned and unversioned release. Also added a specific
description for Ubuntu Preview.
Co-authored-by: Didier Roche <didrocks@ubuntu.com>
=> Revisited descriptions.

.github/workflows/build-wsl.yaml, .github/workflows/detect-update-releases.yaml, .gitignore, go.work, wsl-builder/prepare-assets/go.mod, wsl-builder/prepare-assets/go.sum, wsl-builder/prepare-build/go.mod, wsl-builder/prepare-build/go.sum
Use it for CI and always taking latest modules, as we have multiple modules in this project
=> Use go workspaces

.github/workflows/build-wsl.yaml
=> Fix another typo: the variable name is WSLId not WslID.

.github/workflows/build-wsl.yaml
+ disable the debug flag from the job runs!
=> Fix secrets naming.

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
This is a first proposal to fix #171 . The issue only mentioned bug reports, but I already noticed one enhancement request and I'm sure we can benefit from consistency in both cases.
One can give it a try: https://github.com/CarlosNihelton/github_templates/issues/new/choose
Here are some screenshots:
=> Issue templates

meta/Ubuntu/generated/store/en-us/ProductDescription.xml, meta/Ubuntu/src/store/en-us/ProductDescription.xml, meta/Ubuntu18.04LTS/generated/store/en-us/ProductDescription.xml, meta/Ubuntu20.04LTS/generated/store/en-us/ProductDescription.xml, meta/Ubuntu22.04LTS/generated/store/en-us/ProductDescription.xml, meta/UbuntuPreview/generated/store/en-us/ProductDescription.xml, meta/UbuntuPreview/src/store/en-us/ProductDescription.xml, meta/src/store/en-us/ProductDescription.xml
In the ProductDescription.xml sources.
CI will generate the derivatives from those.
=> Updates link ubuntu.com/wsl for store listing

e2e/test-runner/runner_test.go
This fixes an error that snuck in in #292
=> [Hotfix] Fixed e2e test expectedPolicy

DistroLauncher/DistroLauncher.cpp, DistroLauncher/messages.mc
Syncing with upstream.
Ref.:
https://github.com/microsoft/WSL-DistroLauncher/commit/556225d6d920efbb301abfab8a94f33bb7c624a7
https://github.com/microsoft/WSL-DistroLauncher/pull/117
=> Change WSL to use system error string for WSL OC not present (#117)

.github/workflows/sync-gh-jira.yaml
Use our new component scheme with the Jira layout
=> New component naming scheme for synchronizing bugs

.github/workflows/sync-gh-jira.yaml
This only align spaces and workflow url on this project.
UDENG-308
=> Standardize on Jira automation template

.github/actions/wsl-install/action.yaml, .github/workflows/e2e.yaml
A few issues have arised with our CI since #384 was merged. These are solved here.
=> Fix miscelaneous CI issues

.github/actions/wsl-checkout/action.yaml
It's still not supported, but at least it wont hang forever.
=> Gardening 🌱:  Improve WSL checkout on private repos

.github/actions/wsl-install/action.yaml
See error here:
https://github.com/canonical/ubuntu-pro-for-windows/actions/runs/6182674709/job/16793339194
---
UDENG-988
=> [Actions] Add if clause in case Appx was not installed yet

.github/workflows/sync-gh-jira.yaml
Renamed component from S-WSL to WSL in Jira
=> Renamed component to WSL

docs/guides/index.md, docs/index.md, docs/reference/index.md, docs/tutorials/index.md
Shortened titles and reordered them in the sidebar
=> fix(docs): Fix documentation section names and ordering

.github/actions/README.md, docs/guides/index.md, docs/guides/run-workflows-azure.md, docs/reference/actions.md, docs/reference/distributions.md, docs/reference/index.md
=> docs(actions): Write GitHub actions + Azure docs

meta/Ubuntu20.04LTS/src/DistroLauncher/extended_messages.h
This was not removed during the cleanup of the hacks on the launcher.
=> Cleanup leftover

docs/custom_conf.py
UDENG-3079
Advertise the newly create Matrix channel: https://matrix.to/#/#ubuntu-wsl:ubuntu.com
=> docs: added link to the Matrix channel

DistroLauncher/Ubuntu/InitTasks.cpp
The launcher focus is just protecting cloud-init run. Let's not print a word about it.
At the surface it doesn't seem that anything is different from the original UX, except for the potentially longer setup time.
We rely on wsl-setup and motd to deliver a one-time show warning message if cloud-init reports error (recoverable or not).
See: https://github.com/ubuntu/wsl-setup/pull/14 for more context about this part.
Apart from messaging, no other behaviour is changed.
Considering a condition of partial failure for cloud-init (and experience has shown there are tons of ways to go into a degraded done extended status), we move from this
Into this:
---
Closes UDENG-4111
=> fix: More silent cloud-init runs
